// Code generated by go-swagger; DO NOT EDIT.

// Package restapi thyra-plugin - BlogNoCode
//
//	BlogNoCode plugin API.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/png
//	  - text/css
//	  - text/html
//	  - text/javascript
//	  - application/json
//	  - text/webp
//	  - application/svg+xml
//
// swagger:meta
package restapi
