// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "BlogNoCode plugin API.",
    "title": "thyra-plugin - BlogNoCode",
    "version": "0.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "operationId": "defaultPage",
        "responses": {
          "301": {
            "description": "Move to the default endpoint"
          }
        }
      }
    },
    "/web/{resource}": {
      "get": {
        "produces": [
          "application/json",
          "text/javascript",
          "text/html",
          "text/css",
          "text/webp",
          "image/png",
          "application/svg+xml"
        ],
        "operationId": "web",
        "parameters": [
          {
            "type": "string",
            "description": "Website resource.",
            "name": "resource",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Page found"
          },
          "404": {
            "description": "Resource not found."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "BlogNoCode plugin API.",
    "title": "thyra-plugin - BlogNoCode",
    "version": "0.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "operationId": "defaultPage",
        "responses": {
          "301": {
            "description": "Move to the default endpoint"
          }
        }
      }
    },
    "/web/{resource}": {
      "get": {
        "produces": [
          "application/json",
          "application/svg+xml",
          "image/png",
          "text/css",
          "text/html",
          "text/javascript",
          "text/webp"
        ],
        "operationId": "web",
        "parameters": [
          {
            "type": "string",
            "description": "Website resource.",
            "name": "resource",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Page found"
          },
          "404": {
            "description": "Resource not found."
          }
        }
      }
    }
  }
}`))
}
